# Generated by Django 5.0 on 2025-12-15 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='time',
            field=models.TimeField(default='09:00:00'),
        ),
    ]
